### PR TITLE
Give Credit

### PR DESCRIPTION
**Pull request by H1manshu21**
given credit to my source

### CODE REVIEW

**Comment by SHembram18** [comment]
Okay I will mention the credit..😅🙄🙄😅👍

**Comment by H1manshu21** [comment]
Just merge this code

**Comment by SHembram18** [comment]
What does it mean?
Merge code mean....
How it works?

**Comment by H1manshu21** [comment]
Just click on merge pull request and done. Don't forget to pull your local repository too

**Comment by SHembram18** [comment]
If i accept your **pull request** & **Merge** the code then what you will be change in your **Code**
it will automatically affect on my **_code_**. 
Sorry...................................

**Comment by SHembram18** [comment]
Oh i see you want to add this one :-
                                                            - [Himanshu40/Sorting-Algorithm](https://github.com/Himanshu40/Sorting-Algorithm)   

on my repository..............then its okay.
But still i confused if i merge the code then the other files of your  repository will be copy or not?

**Comment by H1manshu21** [comment]
Nothing gonna harm your repository. Just merge it and no external files will be affected

**Pull request merged**
